### ISSUE TITLE
'JSONModel.h' file not found

### ISSUE THREAD

**Issue by nileshpol18** [citruspay/citruspay-ios-sdk#6]
I tried installing using cocoa pods. After installing, I imported bridging header as #import "CitrusPay/CitrusPay.h"
After compiling it gives an error as  'JSONModel.h' file not found so I had to add this framework manually by dragging respective files and folders.

**Comment by manishgumbal** [comment]
Same issue to me.Please help me out to resolve this issue.

I used cocoapods to install the citrus pay it installs citrus pay and jsonmodel but after that it shows me jsonmodel.h not found

**Comment by mukesh122** [comment]
verify your installation steps here  - https://github.com/citruspay/citruspay-ios-sdk#installation

**Comment by manishgumbal** [comment]
I did the exact installation by using cocoapods, but issue is same. I tried in twice

**Comment by mukesh122** [comment]
This is has been resolved, you can check with latest SDK version.

**Comment by alokvnair** [comment]
Issue is still not resolved. I am getting the same error on integrating v3.6.2 via CocoaPods. Please fix it ASAP.

**Comment by bharath-kamath** [comment]
Still getting the same issue, and now v3.6.2 getting this error Unable to find a specification for `CitrusPay~> 3.6.2`

**Comment by umeshephesoft** [comment]
Facing the same issue on 3.6.2

**Comment by rajatattri-nith** [comment]
Still  not resolved, getting the same issue in v3.6.2, please resolve asap

**Comment by bharath-kamath** [comment]
@umeshephesoft @rajatattri-nith For now i followed the manual installation process and it works. Seems to be an issue with Pod installation.

**Comment by umeshephesoft** [comment]
So what is the way out. Using it manual instead of Pod?

**Comment by bharath-kamath** [comment]
Yes, looks like it. Not ideal but since nobody from citrus is responding about this issue, manual installation is the only way.

**Comment by sourabh-verma-citruspay** [comment]
Probably you can try running
`pod update CitrusPay
`

I am attaching a sample project built 5 mins back which uses cocoapods and its pulling JSONModel dependency properly

https://drive.google.com/file/d/0B7UDdmMtZAI0WWMxZW9zN3gtVFU/view?usp=sharing

**Comment by umeshephesoft** [comment]
Hi Sourabh

Can you please explain the steps you followed?

Or are those the same followed as explained in your documentation. We were
using cocoapods Citrus version 3.6.2



--
Regards,
Umesh Sharma | Lead Engineer

M| +91 8427833268

https://in.linkedin.com/in/umesh-sharma-5a0ab962
<https://www.linkedin.com/in/indrasensingh>



*  Smart Capture™ Innovations*

LinkedIn <http://www.linkedin.com/company/ephesoft-inc.> - Twitter
<http://twitter.com/ephesoft> - Facebook <http://www.facebook.com/ephesoft>

*Ranked No. 418 by Inc Magazine
<http://ephesoft.com/press-releases/ephesoft-named-to-inc-500-list-of-fastest-growing-private-companies>*

*This email and any files transmitted is bound by the **Ephesoft Email
Confidentiality Disclaimer
<https://na34.salesforce.com/sfc/p/61000000dQko/a/61000000KzHL/666IAdFme.9C9g2ISPHc66nNVdmosdTt8nGliw2FTes>*

**Comment by sourabh-verma-citruspay** [comment]
I have not done anything special. 

## Steps Tried
1. I created a new project and workspace.
2. `cd <Project Folder>`
3. `pod init`
4. `pod install`
5. Added CitrusPay in pod file My podFile looks like this (I did try V3.6.2 too)

```
target 'CitrusPayPodTest' do
    pod 'CitrusPay', '~> 3.6.3'
end
```
6. Ran `pod install` again
7. I added `#import <CitrusPay/CitrusPay.h>` in bridging header file because library is in obj-c and project is swift

## Probable Causes
My guess is that maybe you used an older version of library before which had JSONModel dependency bug and for some reason its not getting pulled even after updating version at your end. So i would advise you to clean the pod installation for CitrusPay. Try `pod update` or try `pod outdated`
https://guides.cocoapods.org/using/pod-install-vs-update.html

If this isn't solving the problem let me know.

## Pod update Sample
When you execute pod update, you should see JSONModel automatically in it as per this screenshot

<img width="557" alt="screen shot 2016-07-31 at 5 03 02 pm" src="https://cloud.githubusercontent.com/assets/17001096/17276252/cf48fe28-5740-11e6-82a6-1504350f4a20.png">

**Comment by umeshephesoft** [comment]
Still Unable to use it using Pod Install. I tried with version 3.6.3.





--
Regards,
Umesh Sharma | Lead Engineer

M| +91 8427833268

https://in.linkedin.com/in/umesh-sharma-5a0ab962
<https://www.linkedin.com/in/indrasensingh>



*  Smart Capture™ Innovations*

LinkedIn <http://www.linkedin.com/company/ephesoft-inc.> - Twitter
<http://twitter.com/ephesoft> - Facebook <http://www.facebook.com/ephesoft>

*Ranked No. 418 by Inc Magazine
<http://ephesoft.com/press-releases/ephesoft-named-to-inc-500-list-of-fastest-growing-private-companies>*

*This email and any files transmitted is bound by the **Ephesoft Email
Confidentiality Disclaimer
<https://na34.salesforce.com/sfc/p/61000000dQko/a/61000000KzHL/666IAdFme.9C9g2ISPHc66nNVdmosdTt8nGliw2FTes>*

**Comment by sourabh-verma-citruspay** [comment]
I need you to answer few questions
1) Are you using .xcworkspace or .xcodeproj file to build the project
2) Can you run pod install and share console logs
3) Can you share your PodFile listing all pods associated with your project

**Comment by umeshephesoft** [comment]
Hi Sourabh

We are using .xcworkspace for our project.

We have the following pods installed

platform :ios, '8.0'
use_frameworks!

target 'UniShop' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Google/SignIn'
pod ’SVProgressHUD’
pod 'IQKeyboardManagerSwift'

end

I have attached the logs.



--
Regards,
Umesh Sharma | Lead Engineer

M| +91 8427833268

https://in.linkedin.com/in/umesh-sharma-5a0ab962
<https://www.linkedin.com/in/indrasensingh>



*  Smart Capture™ Innovations*

LinkedIn <http://www.linkedin.com/company/ephesoft-inc.> - Twitter
<http://twitter.com/ephesoft> - Facebook <http://www.facebook.com/ephesoft>

*Ranked No. 418 by Inc Magazine
<http://ephesoft.com/press-releases/ephesoft-named-to-inc-500-list-of-fastest-growing-private-companies>*

*This email and any files transmitted is bound by the **Ephesoft Email
Confidentiality Disclaimer
<https://na34.salesforce.com/sfc/p/61000000dQko/a/61000000KzHL/666IAdFme.9C9g2ISPHc66nNVdmosdTt8nGliw2FTes>*

**Comment by sourabh-verma-citruspay** [comment]
@nileshpol18  @manishgumbal @alokvnair  @bharath-kamath  @rajatattri-nith  :  Can you share updates from ur end too.

@umeshephesoft : 
1. Can you share logs too. Its not attached.
2. Can you clean your project and share me the screenshot of the error with pod.

**Comment by umeshephesoft** [comment]
HI Sourabh

Attaching pod file and screenshot of terminal. Also attaching issue in
project.



--
Regards,
Umesh Sharma | Lead Engineer

M| +91 8427833268

https://in.linkedin.com/in/umesh-sharma-5a0ab962
<https://www.linkedin.com/in/indrasensingh>



*  Smart Capture™ Innovations*

LinkedIn <http://www.linkedin.com/company/ephesoft-inc.> - Twitter
<http://twitter.com/ephesoft> - Facebook <http://www.facebook.com/ephesoft>

*Ranked No. 418 by Inc Magazine
<http://ephesoft.com/press-releases/ephesoft-named-to-inc-500-list-of-fastest-growing-private-companies>*

*This email and any files transmitted is bound by the **Ephesoft Email
Confidentiality Disclaimer
<https://na34.salesforce.com/sfc/p/61000000dQko/a/61000000KzHL/666IAdFme.9C9g2ISPHc66nNVdmosdTt8nGliw2FTes>*

**Comment by xorforce** [comment]
Hey, tried pod install with v3.7 , still issue of "JSONModel.h" not found. Has anybody found a solution yet?

**Comment by alokvnair** [comment]
@xorforce add the library and not via CocoaPods. It is the only solution available at present. I think  Citrus has no time to look into and fix this basic issue.

**Comment by xorforce** [comment]
@alokvnair Have you been able to use the manual method successfully? I am getting an error "CitrusPay/CitrusPay.h" not found.
